Corrected Crouton Filter
swarmauri/crouton pull request #13
Opened 2024-11-14 06:50 UTC by samie-ya

* Filter made to return List of Models

2024-11-20 11:30 UTC, samie-ya commented
> please reach out to discuss the use case in more detail

Hi, Coby.
When I started modifying crouton, I made sure it returned a Single Model when it used Query. But on the other endpoints, I had to use the Query to return multiple models. So I reversed it to it's Original return value of List[Model], for with and Without Query

2024-11-28 09:57 UTC, samie-ya commented
> please reach out to discuss the use case in more detail

@cobycloud 
Hey Coby, Can we discuss these changes?

2024-11-30 00:23 UTC, cobycloud requested changes

2024-11-30 00:23 UTC, cobycloud commented on pkgs/crouton_client/crouton_client/blocking.py
My understanding is that we are creating a custom delimiter so that we can pass the query string as a query string.  This seems like a non-standard workaround. Would like for us to revisit the approach to determine a standardized sustainable solution.

2024-12-10 17:53 UTC, closed without merging